language: python

sudo: false

matrix:
    include:
        -   python: 3.5
            env: TOXENV=style,py35
        -   python: 3.6
            env: TOXENV=py36

install:
    - pip install tox

script:
    - tox
